# This file was generated by GoReleaser. DO NOT EDIT.
cask "moco" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "aca4ea4fc0f165644ac8fe0bf0fcd253d68cc750964802e651f92ba320a5347e"
      url "https://github.com/whatwedo/moco-cli/releases/download/v#{version}/moco-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4db799584243c26b7ce625f4dc7ed83babb84884c6fde7a2f3d979369590e4ac"
      url "https://github.com/whatwedo/moco-cli/releases/download/v#{version}/moco-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d881f465d4716d83d12e3159b5e5f3b2770a3f5fbc057a809c124ef9c79d58cd"
      url "https://github.com/whatwedo/moco-cli/releases/download/v#{version}/moco-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bca652242919546b12395e84cd2259cb30e5a3f5cde6bc98e4e5e02439c7aec"
      url "https://github.com/whatwedo/moco-cli/releases/download/v#{version}/moco-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moco"
  desc "Command-line client for the MOCO API v1"
  homepage "https://github.com/whatwedo/moco-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/moco"]
    end
  end

  # No zap stanza required

end
